export const reviews = [
  {
    author: "Amarasena Ranasinghe",
    text: "SLEEPERWOOD Villa is very attractive place to enjoy the freedom .This location is very closer to Unawatuna . This villa is located at very charming environment .There is nice garden is surrounded by the the villa with many trees ,shading of these tress provide additional comfort and freedom to the visitors.. There are many birds and squirrels can be seen throughout the day. This villa is equipped with all the facilities that deemed to satisfy any class of foreign visitors. Rooms are also very attractive and neat including air-conditioning. Cleanliness and neatness is their theme and they also good service providers .If you come to Unawatuna do not forget stay and enjoy the good and restful night ,this may be the place to change your life into new experience in southern Sri Lanka\n\nThere are many tourist attraction places are also near by Unawtuna beach ,Archaeological sites , corals ,surfing ,visiting of Ramaala connected to the famous Story RAMAYANAYA are the main interesting areas and that can be visited and enjoyed easily .Greater Sri Lankan Scientist Dr Arthur C Clark also Had a great interested about Unawatuna beach, and also one of greatest movie screened at Unawatuna and Dr Arthur C Clark also in that movie",
    ratings: { rooms: 5, service: 5, location: 5 },
  },
  {
    author: "Elena K",
    text: "Everything is great. The shower is gorgeous, I really liked it, I want the same one now with flowers and sunlight))\nEverything is clean and tidy. There were days when we were alone in the villa, it turns out that the whole villa is at our disposal for the price of a room. There is a refrigerator, a stove and a washing machine. The water is warm, good and the pressure is good.\nThe owner is very friendly, he helped us buy train tickets. He offered to organize excursions or a taxi, but I mainly ordered everything through PickMe. The villa is located a little further from the road, which is great, there is no road noise and dust. The air conditioning works well. The territory of the villa is beautiful and well-kept. The owner is for separate waste collection. Beautiful birds fly to the territory and chipmunks run around. Once we saw monkeys on the territory and on the road to the beach. Monitor lizards also crossed the road. We walked along the beach with turtles to the beach, the road is beautiful and interesting. Turtles swim along the entire coast where there are stones with algae, they eat them. Overall the villa is great, price 🔥, owner 😎 everything is super. Thank you.",
    ratings: null,
  },
  {
    author: "Айгуль Сунагатуллина",
    text: "We rested here from 11-20.02.2024. The villa is new, equipped with everything you need: air conditioning and private bathrooms in each of the three bedrooms, mosquito nets on the beds, a closet with a key, a large dining table in the kitchen, a refrigerator, a stove, an electric kettle, all the dishes and even a washing machine! The windows offer a beautiful view of the palm garden, and there is also a veranda outside where you can comfortably spend time.\nVery nice and responsive hosts - always in touch, answer all questions, help with everything, solve everyday issues.\nUnawatuna Beach is a 10-15 minute walk; in the other direction, in the same time, you can walk to the turtle beach and a popular place with a swing on a palm tree.\nThe only alcohol market in Unawatuna with good prices is also located 10 minutes from the villa on the way to the beach, and there are fruit shops nearby. There are a lot of cafes nearby - there is always somewhere to eat deliciously.\nI definitely recommend this villa! Everything was just great!",
    ratings: null,
  },
];

